### ISSUE TITLE
All features overridden by cart

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#12]
For some reason all the features says they are overridden - even though they are not.

**Comment by googletorp** [comment]
This is a known bug in features

**Comment by lsolesen** [comment]
https://drupal.org/node/2056351 <-- other than this?

**Comment by googletorp** [comment]
Features is not perfect and can sometimes mark something as overridden, eventhough it's not.

**Comment by lsolesen** [comment]
This was actually a bug in the way the cart view was overridden in code.
