### ISSUE TITLE
Cannot upgrade from 0.2 to latest version

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#16]
I am trying to migrate to the latest code in my production environment.

On BOA I am getting this:

```
WD vih_short_course: field_featured_image was added successfully to short_course_type
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.type' in 'where clause'
```

I am guessing that it has something to do with the order the upgrades are run in, and thus we have to introduce $dependencies in the distro install file?

More from the log here:

WD vih_short_course_kayak: field_featured_image was added successfully to vih_short_course_kajak
WD i18n_string: Deleted string field:field_picture:vih_short_course_kajak:label for text group field: Billede
Executing vih_short_course_family_update_7000
WD i18n_string: Created string field:field_featured_image:vih_short_course_family:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:vih_short_course_family:label for text group field: Featured image
WD vih_short_course_family: field_featured_image was added successfully to vih_short_course_family
WD i18n_string: Deleted string field:field_picture:vih_short_course_family:label for text group field: Billede
Executing vih_short_course_update_7000
WD i18n_string: Created string field:field_featured_image:short_course:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:short_course:label for text group field: Featured image
WD vih_short_course: field_featured_image was added successfully to short_course
WD i18n_string: Deleted string field:field_picture:short_course:label for text group field: Billede
Executing vih_short_course_update_7001
WD i18n_string: Created string field:field_featured_image:short_course_type:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:short_course_type:label for text group field: Featured image
WD vih_short_course: field_featured_image was added successfully to short_course_type
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.type' in 'where clause'
Executing vih_golf_courses_update_7000
WD i18n_string: Created string field:field_featured_image:vih_short_course_golf:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:vih_short_course_golf:label for text group field: Featured image
WD vih_golf_courses: field_featured_image was added successfully to vih_short_course_golf
WD i18n_string: Deleted string field:field_picture:vih_short_course_golf:label for text group field: Billede
Executing vih_golf_courses_update_7001
WD i18n_string: Created string field:field_featured_image:vih_golf_courses:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:vih_golf_courses:label for text group field: Featured image
WD vih_golf_courses: field_featured_image was added successfully to vih_golf_courses
WD i18n_string: Deleted string field:field_picture:vih_golf_courses:label for text group field: Billede
Executing vih_employees_update_7000
WD i18n_string: Created string field:field_featured_image:employee:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:employee:label for text group field: Featured image
WD vih_employees: field_featured_image was added successfully to employee
WD i18n_string: Deleted string field:field_profile_picture:employee:label for text group field: Billede
Executing vih_employees_update_7001
WD i18n_string: Created string field:field_featured_image:employee_context:label for text group field: Featured image
WD i18n_string: Created string field:field_featured_image:employee_context:label for text group field: Featured image
WD vih_employees: field_featured_image was added successfully to employee_context
WD i18n_string: Deleted string field:field_profile_picture:employee_context:label for text group field: Billede
WD i18n_string: Deleted string field:field_profile_picture:employee_context:description for text group field: Upload et profilbillede som passer til læreren i denne sammenhæng.
Executing vih_deploy_update_7015
WD features: Reverting vih_commerce / field_instance.
WD features: Revert completed for vih_commerce / field_instance.
WD features: Reverting vih_short_course / field_instance.
WD features: Revert completed for vih_short_course / field_instance.
WD features: Reverting vih_short_course_commerce / field_instance.
WD i18n_string: Updated string field:field_featured_image:short_course_basic:label for textgroup field: Billede
WD i18n_string: Updated string field:field_featured_image:short_course_basic:label for text group field: Billede
WD features: Revert completed for vih_short_course_commerce / field_instance.
WD features: Reverting vih_short_course_sport / variable.
WD features: Revert completed for vih_short_course_sport / variable.
WD features: Reverting vih_golf_courses / field_base.
WD features: Revert completed for vih_golf_courses / field_base.
WD features: Reverting vih_golf_courses / field_instance.
WD features: Revert completed for vih_golf_courses / field_instance.
WD features: Reverting vih_golf_courses / views_view.
WD features: Revert completed for vih_golf_courses / views_view.
WD features: Reverting vih_employees / field_instance.
WD features: Revert completed for vih_employees / field_instance.
WD features: Reverting vih_employees / page_manager_handlers.
WD features: Revert completed for vih_employees / page_manager_handlers.

**Comment by mglaman** [comment]
Found...
- https://drupal.org/node/1267748
- https://drupal.org/node/1256888

Something about running update.php. However, BOA should be doing that, right? I don't know the BOA upgrade path but sounds like schema cache issue

**Comment by lsolesen** [comment]
But I am not using UUID module as far as I know?
