### ISSUE TITLE
Date, time and author should be shown on stories

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#24]
Right now date and author is not shown on stories in production. Production is probably panelized (which development is not). It should be shown.

**Comment by mglaman** [comment]
@lsolesen do you have a link to a live story for reference? Or a way to be able to troubleshoot this (can't find an instance in prod)

EDIT:

Nevermind - https://vih.dk/nyhed/tidlig-tilmelding-giver-rabat-0

It's Panelized to have specific fields, just need to add submitted pane.

**Comment by lsolesen** [comment]
Every instance under vih.dk/nyheder.
Den 05/03/2015 02.24 skrev "Matt Glaman" notifications@github.com:

**Comment by mglaman** [comment]
@lsolesen ok, cool. I've got it all set however I don't hve access to commit on vih_plugins or vih_stories to get fixes up.
