### ISSUE TITLE
Menu getting too wide

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#30]
On e.g. vih.dk/langekurser

![skaermbillede 2015-03-07 kl 16 42 19](https://cloud.githubusercontent.com/assets/148026/6541943/093cd79e-c4e9-11e4-978b-a430e170db5e.png)

**Comment by cornifex** [comment]
7d9939bd2c69c3e2730859ff2535420b7212b660 fixes this by changing white-space to normal

**Comment by cornifex** [comment]
vih/sport_2014.7d9939bd2c69c3e2730859ff2535420b7212b660 Fixes this by setting white space to normal.

**Comment by cornifex** [comment]
vih/sport_2014@7d9939bd2c69c3e2730859ff2535420b7212b660 fixes this by setting white space to normal

**Comment by lsolesen** [comment]
@mglaman This is still a problem in IE.

**Comment by mglaman** [comment]
@lsolesen which version of IE? Just loaded up Browser stack and looked at vih.dk/langekurser on IE9 and IE10 and IE11 in Windows 7 and can't see error.

**Comment by lsolesen** [comment]
It even happens in Chrome on MacOS? You need to hover e.g. 'Lange kurser' which has very long sub items.

**Comment by mglaman** [comment]
Found out why! Didn't happen on li.active, which I was on.

**Comment by lsolesen** [comment]
I still got this on Chrome on MacOs?

**Comment by mglaman** [comment]
:/ because in vih/sport_2014@4420eb3 I just committed the sass and did not compiled.
