### ISSUE TITLE
Make sure that tests passes on Travis CI - and features are not overridden on production

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#42]

**Comment by mglaman** [comment]
Need access to vih_short_course_family], @lsolesen

**Comment by mglaman** [comment]
Note: committing and will update vih-build at once

**Comment by mglaman** [comment]
Need access to vih_facilities @lsolesen

**Comment by lsolesen** [comment]
@mglaman Access granted to both.

**Comment by mglaman** [comment]
VIH Dashboard will remain broken until the field field_webform_category is exported from Webforms (and the taxonomy.) Not sure where you think this should go? (Also would need to get database dump in order to properly export)

**Comment by lsolesen** [comment]
Tests passes on Travis.
