### ISSUE TITLE
Bringing submenu items closer to original proposal

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#43]
Could you bring the submenu items a little closer to the original proposal:

https://github.com/vih/sport_2014/issues/1

![korte_kurser__sommerkurser_og_hojskole___site-install](https://cloud.githubusercontent.com/assets/124599/5162984/8023e038-73df-11e4-8c71-ae55bb0b7fc1.png)

**Comment by cornifex** [comment]
Latest commit fixes dropdowns to look like this:

![screenshot from 2015-03-29 17 40 16](https://cloud.githubusercontent.com/assets/7952198/6888160/e95a2c70-d63a-11e4-8678-2d0c5ac5e816.png)
