### ISSUE TITLE
Order of teachers wrong

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#47]
On e.g. https://vih.dk/kortekurser/fitness-360-uge-29-2015-3076 the order of the the teachers are wrong. On the entityreference on the node edit, Lars Olesen, Mette Bjerre, Thea Rasmussen is the order, but in display it is the exact opposite.

**Comment by mglaman** [comment]
@lsolesen so I was giving this a run locally. Altering the field value orders was also adjusting the View's output.

**Comment by mglaman** [comment]
@lsolesen so I got it to reproduce locally. This sort change made it work locally.

**Comment by lsolesen** [comment]
In production this is still sorted in the wrong way? https://vih.dk/kortekurser/fitness-360-uge-29-2015-3076 (This is exactly oppostite of what it should be) @mglaman Could you have a look at this again?
