### ISSUE TITLE
Course names too big

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#51]
http://vih.dk/kortekurser

The size in the sidebar of the course names are too big.

![sidebar-size](https://cloud.githubusercontent.com/assets/148026/6668730/0084356c-cbf5-11e4-92c4-1cf49bb74001.png)

**Comment by mglaman** [comment]
@lsolesen maybe I'm oblivious, but I don't see that on https://vih.dk/kortekurser ?

**Comment by lsolesen** [comment]
Its in the sidebar. When you are on a course. Right now no courses are available, so it does not show.
