### ISSUE TITLE
The news should have dates on the page

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#54]
It should be obvious whether the news are new or old!

**Comment by mglaman** [comment]
@lsolesen  I believe this was done before - vih/vih_stories@ec4a683c1c64aec2dc168d7c1456b72e0bfbcc21

I wonder if the Feature is overridden? I exported to Panelizer.

**Comment by mglaman** [comment]
Linking to vih/vih-build#24.

**Comment by mglaman** [comment]
I quick checked, and in production it is overridden. The Panelizer component needs to be reverted.
