### ISSUE TITLE
Forms on vih.dk not showing

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#55]
I've looked in the database, and it seems that all the components are there, but they are gone from the interface. Also node/*/edit is blank for the webforms. 

It happened after upgrading from webform 4.3 to 4.7 last night.

**Comment by lsolesen** [comment]
This is a little of an emergency as all our registration is currently not working.

**Comment by mglaman** [comment]
Quickfix is https://www.drupal.org/node/2465159#comment-9796871. Need to see if Webform requires patch.

**Comment by lsolesen** [comment]
I've did an update to latest code today, and the forms seems to stay, so this is fixed at least for vih.dk.
