### ISSUE TITLE
Subjects are not responding well

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#57]
vih.dk/fag is not nice on mobile.

**Comment by mglaman** [comment]
@lsolesen so the issue seems to be the grid plugin. It's specifying 4 columns, which drops in col-md-3 (4*3=12). However it's adding col-xs-2..which I wonder if it means to do col-xs-6 (half).

Not sure what's providing the Grid style plugin, but looks like the logic in there is root of the issue.
