### ISSUE TITLE
Videoes are pushing right sidebar

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#59]
https://vih.dk/fag/fodbold

![skaermbillede 2015-05-04 kl 22 40 55](https://cloud.githubusercontent.com/assets/148026/7462024/d9bb335a-f2ae-11e4-82b1-e0ccbdfbd928.png)

**Comment by mglaman** [comment]
@lsolesen what browser is this happening in? IE? Not showing up in Chrome at the moment.

**Comment by mglaman** [comment]
Actually, with #56 this might be resolved anyways.

**Comment by lsolesen** [comment]
Closing this for now.
