### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#61]
I've created the social links block on vih.dk manually just through WYSIWYG editor. However it keeps breaking - and right now the size exploded. 

Will the best way just be to create a block programatically or what do you say?

**Comment by lsolesen** [comment]
There is a snippet here, that might solve this: https://gist.github.com/lsolesen/8e38ebbc7201d8f8378e

And there is some work I started a while ago here: https://github.com/vih/vih_plugins/tree/social-links

I need to get vih.dk footer to look with nicer social media. I am thinking this approach is sound. I like how the links looks on glamanate.com. @mglaman Could you make it work :)

**Comment by mglaman** [comment]
![screenshot from 2015-09-23 22 20 53](https://cloud.githubusercontent.com/assets/3698644/10064769/c3e0acec-6241-11e5-9e84-4e6a31f5510e.png)

Here's a screenshot preview of what it looks like now if placed. Links need some coloring. I would recommend replacing footer with a mini panel and dropping in panes that way. But this should be good to go. Can merge branch in if you'd like, or if you want to, or if any immediate feedback.

**Comment by lsolesen** [comment]
It would be cool with replacing the footer with something, so it is possible to drop in panes. Maybe also the right sidebar, it would be nice.

**Comment by mglaman** [comment]
Using a mini panel as my block that goes in the footer has been my go to solution for a while. Let me know if you have a preference to a module to export it to, or if you plan on making a new one such as "vih_footer".

Can export it like you have now plus the new social links

**Comment by lsolesen** [comment]
Whatever you think will be the best option. Thanks!

**Comment by mglaman** [comment]
Hm. I think it might make sense to just make a new repo called vih_footer. If you spin that up and grant me access I will merge the social-links branch in on vih_plugins and export the footer mini panel with that pane and mimic existing footer.

Then you'll just need to swap out the blocks in production for the mini panel block

**Comment by lsolesen** [comment]
Here: https://github.com/vih/vih_footer

**Comment by mglaman** [comment]
@lsolesen I guess I don't have access to push on vih_deploy! Have an update hook to enable vih_footer. I noticed the theme's footer is set to 3, 7, 2. In order for this to work I'll need to change one of them to col-md-12 so that the Panels layout can work it's magic. That OK?

**Comment by lsolesen** [comment]
@mglaman Access granted.
