### ISSUE TITLE
Lectures PDF should take care of page breaks etc

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#71]
Right now the page needs to be a certain length to be on one poser. Sometimes we need more text - like https://vih.dk/foredrag/udflugt-til-trapholt-0 causing this ugly pdf https://vih.dk/node/3475/pdf

**Comment by lsolesen** [comment]
This cannot be solved before https://github.com/vih/vih-build/issues/83 is solved - as this is blocking development.

Edit: This has been fixed in https://github.com/vih/vih_lectures_pdf/commit/999bd8f94f6f77d6c69bf9d69757f901ad5e4dc8

**Comment by lsolesen** [comment]
There is some info here: http://stackoverflow.com/questions/1078729/how-to-calculate-the-height-of-a-multicell-writehtmlcell-in-tcpdf

**Comment by mglaman** [comment]
I don't have access to vih_lectures_pdf. Here is a patch which fixes it up, plus example.

PDF: https://glamanate.com/sites/default/files/foredrag.pdf

Patch: https://gist.github.com/mglaman/3d50b08ee7b069c4c068

**Comment by lsolesen** [comment]
@mglaman Access granted!
