### ISSUE TITLE
Problems with the Viggo importer again

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#86]
```
Exception: Download of https://vejle.viggo.dk/ExportCalendar/?ViggoId=87&amp;UserId=298&amp;code=17bca452d0b19b39a49d3ffdc1a77faabe5ae617 failed with code 0. i FeedsHTTPFetcherResult->getRaw() (linje 33 af /data/disk/o5189739716/static/vih-20150625/sites/all/modules/contrib/feeds/plugins/FeedsHTTPFetcher.inc).
```

**Comment by lsolesen** [comment]
@mglaman The calendar issue on both vies.dk and vih.dk is kind of pressing. I was wondering if it was possible to just get the two files down to a another non encrypted server and then just get it from there instead. 

Maybe it would be possible just on my codio box?

**Comment by lsolesen** [comment]
I've added you to https://codio.com/lsolesen/VIH-Calendar-Always-on-Box/
@mglaman Could you get this working today?

**Comment by mglaman** [comment]
That would be the way to do it, like a proxy

**Comment by mglaman** [comment]
print file_get_contents(); with the URL should do fine

**Comment by lsolesen** [comment]
After switching to http://genesis-sheriff.codio.io:3000/vih.php as my source of import, I get the following:

```
Exception: Download of http://genesis-sheriff.codio.io:3000/vih.php failed with code -10060. i FeedsHTTPFetcherResult->getRaw() (linje 52 af /data/disk/o5189739716/static/vih-20150629/sites/all/modules/contrib/feeds/plugins/FeedsHTTPFetcher.inc).
```

**Comment by lsolesen** [comment]
@mglaman If we cannot get this to work (I see that the code is another code -10060), we need to create a stand - alone website where the calendar can be seen.

**Comment by lsolesen** [comment]
I've done some preliminary work using slimphp. Will investigate further.

**Comment by lsolesen** [comment]
I've created a standalone app here: https://github.com/vih/vih-viggo-standalone. Would be great if we could just invoke the standalone app, if there is a problem with the original feeds import?

**Comment by lsolesen** [comment]
@mglaman Seems that right now, the Viggo import works again. That is after the recent BOA upgrade 2.4.6
