### ISSUE TITLE
Error on all pages - cannot login

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#88]
After upgrading yesterday and the BOA instance was also updated, an error is shown on all pages.

See https://vih.dk

@mglaman Can you help quickly?

**Comment by lsolesen** [comment]
This seems to be the root of the issue - caused by Redirect update --> added in Panopoly_Seo beta2

https://www.drupal.org/node/2515734

**Comment by lsolesen** [comment]
I reverted to Redirect rc1 for a quick fix. The proper fix would probably be to add the status column, which for some reason is not added?

**Comment by lsolesen** [comment]
Found the definition for the column here: http://cgit.drupalcode.org/redirect/tree/redirect.install#n311

**Comment by mglaman** [comment]
When migrating did redirect_update_7101 not run? What's the schema version

**Comment by mglaman** [comment]
Dave Reid made a commit which should fix this.

I'll update Panopoly SEO to include this revision: http://cgit.drupalcode.org/redirect/commit/?id=8cb3a22

**Comment by mglaman** [comment]
Actually RC3 was released
