### ISSUE TITLE
Picture expands area for content shifting the sidebar

### ISSUE THREAD

**Issue by lsolesen** [vih/vih-build#91]
@mglaman Can you please fix this pretty quickly.

![long-courses-error](https://cloud.githubusercontent.com/assets/148026/9928582/7da56f66-5d27-11e5-9942-45169f2713d2.png)

**Comment by lsolesen** [comment]
@mglaman This is a problem in IE - not in Chrome.

**Comment by mglaman** [comment]
Arg again?

**Comment by mglaman** [comment]
Last fix was for media-element embeds, now that I recall.
